# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Xin Feng's Homepage
description: >- # this means to ignore newlines until "baseurl:"
  Xin Feng's personal academic homepage.
baseurl: "" # the subpath of the site
url: "https://funkdub.github.io/fengx.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/profile.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: fengx_hit@outlook.com
    - type: keybase
      value: Google scholar
      link: "https://scholar.google.com/citations?user=dkfbz90AAAAJ&hl=en"
  follow:
    - type: twitter
      name: Twitter
      link: https://x.com/FengxHit
      username: "@YourTwitterUsername"
    #- type: facebook
    #  name: Facebook
    #  link: http://facebook.com/YourFacebookUsername
    #- type: linkedin
    #  name: LinkedIn
    #  link: http://linkedin.com/in/YourLinkedInUsername
    - type: github
      name: GitHub
      link: https://github.com/funkdub
    #- type: dribbble
    #  name: Dribbble
    #  link: https://dribbble.com/YourDribbbleUsername
    #- type: rss
    #  name: RSS
    #  link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
